version: 2

updates:

  - package-ecosystem: "gradle"
    target-branch: "main"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "03:00"
      timezone: "Etc/UTC"
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-major", "version-update:semver-minor" ]

  - package-ecosystem: "gradle"
    target-branch: "6.1.x"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "03:00"
      timezone: "Etc/UTC"
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
