spring:
  security:
    saml2:
      relyingparty:
        registration:
          one:
            signing.credentials: &rp-metadata
              - private-key-location: classpath:credentials/rp-private.key
                certificate-location: classpath:credentials/rp-certificate.crt
            identityprovider:
              metadata-uri: https://simplesaml-for-spring-saml.apps.pcfone.io/saml2/idp/metadata.php
          two:
            signing.credentials: *rp-metadata
            decryption.credentials: *rp-metadata
            identityprovider:
              metadata-uri: https://simplesaml-for-spring-saml.apps.pcfone.io/saml2/idp/metadata.php


logging.level:
  org.springframework.security: TRACE
