logging.level:
  org.springframework.security: TRACE

spring:
  security:
    filter:
      dispatcher-types: async, error, request, forward
    saml2:
      relyingparty:
        registration:
          sp:
            entity-id: "http://localhost:8080/saml2/service-provider-metadata/one"
            singlelogout:
              binding: POST
              url: "http://localhost:8080/saml/logout"
              responseUrl: "http://localhost:8080/saml/SingleLogout"
            acs:
              location: "http://localhost:8080/saml/SSO"
            assertingparty.metadata-uri: https://dev-05937739.okta.com/app/exk598vc9bHhwoTXM5d7/sso/saml/metadata
